"""Add Subject table and many-to-many relationship

Revision ID: 2a2001b63f32
Revises: 4819c765ddd0
Create Date: 2025-10-20 13:48:48.584411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a2001b63f32'
down_revision: Union[str, Sequence[str], None] = '4819c765ddd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
